### ISSUE TITLE
Attach embbed images

### ISSUE THREAD

**Issue by clissmancamacho** [WadeShuler/yii2-sendgrid#3]
Hello Wadeshuler, your complement is very good, I congratulate you. One question, I would like to see the company logo on the email that I sent. But I do not find how. Is there a way to do it? Thank you

**Comment by WadeShuler** [comment]
When sending emails, especially bulk emails (one email to hundreds or thousands of people) it is best to keep the email size small. Embedding images greatly increases the size of the email.

While it is possible to embed images, it would be much better to link to them using normal HTML. Example:

    <img src="https://cdn.example.com/email/images/logo.png">

You notice in my example, I use a "cdn" sub-domain. It is easy to use Amazon S3, CloudFront, and map your own subdomain to them as your own CDN. This isn't necessary, but would greatly increase the speed/loading time of the images. There are tons of tutorials on how to build your own CDN, so I won't go into that.

I personally never embed images.
